src/models.py
from . import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    full_name = db.Column(db.String(150))

src/__init__.py
from os import path
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_toastr import Toastr
from flask_login import LoginManager
import logging

logger = logging.getLogger(__name__)

db = SQLAlchemy()
toastr = Toastr()
DATABASE_NAME = "database.db"


def create_app() -> Flask:
    app = Flask(__name__)

    app.config["SECRET_KEY"] = "secret"
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DATABASE_NAME}"

    db.init_app(app)
    toastr.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    from .models import User

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app: Flask) -> None:
    if not path.exists("src/" + DATABASE_NAME):
        db.create_all(app=app)
        logger.info("Database Initialized!")

src/auth.py
from flask import (
    Blueprint,
    Response,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from flask_login import login_user, current_user, logout_user

auth = Blueprint("auth", __name__)


@auth.get("/login")
def login() -> str:
    return render_template("login.html", user=current_user)


@auth.post("/login")
def login_post():
    email = request.form.get("email")
    password = request.form.get("password")

    user = User.query.filter_by(email=email).first()
    if user:
        if check_password_hash(user.password, password):
            flash("Logged in successfully!", category="success")
            login_user(user, remember=True)
            return redirect(url_for("views.homepage"))
        else:
            flash("Incorrect Email or Password, Try Again!", category="error")
    else:
        flash("Email doesn't exist!", category="error")
    return render_template("login.html", user=current_user)


@auth.get("/signup")
def signup() -> str:
    return render_template("signup.html", user=current_user)


@auth.post("/signup")
def signup_post():
    email = request.form.get("email")
    full_name = request.form.get("name")
    password1 = request.form.get("password1")
    password2 = request.form.get("password2")

    user = User.query.filter_by(email=email).first()
    if user:
        flash("Email already exists.", category="error")
    elif password1 != password2:
        flash("Passwords don't match!", category="error")
    elif len(password1) < 7:
        flash("Password is too short, keep the password above 7 characters.")
    else:
        new_user = User(
            email=email,
            password=generate_password_hash(password1, method="sha256"),
            full_name=full_name,
        )
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember=True)
        flash("Account created successfully!", category="success")
        return redirect(url_for("views.homepage"))

    return render_template("signup.html", user=current_user)


@auth.get("/logout")
def logout() -> Response:
    logout_user()
    flash("Logged out!", category="success")
    return redirect(url_for("views.homepage"))

src/views.py
from flask import Blueprint, render_template
from flask_login import current_user, login_required

views = Blueprint("views", __name__)


@views.get("/")
def homepage():
    return render_template("index.html", user=current_user)


@views.get("/profile")
@login_required
def profile():
    return render_template("profile.html", user=current_user)


@views.get("/classes")
@login_required
def classes():
    return render_template("classes.html", user=current_user)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Attendy{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Dongle:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/homepage.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
    {{ toastr.include_jquery() }}
    {{ toastr.include_toastr_css() }}
    {{ toastr.message() }}
  {% block head %}
  {% endblock %}
</head>
<body>
  {{ toastr.include_toastr_js() }}
  <nav>
    <div class="logo"><a href={{url_for("views.homepage")}}>Attendy</a></div>
    <div class="main">
    <input type="checkbox" id="click">
    <label for="click" class="menu-btn">
      <i class="fas fa-bars"></i>
    </label>
    <ul>
      <li><a href={{url_for("views.homepage")}}>Home</a></li>
      <li><a href="#">Classes</a></li>
      <li><a href={{url_for("views.profile")}}>Profile</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
</div>
    <div class="login-signup">
      <ul id="log-sig">
        {% if user.is_authenticated %}
        <li><a href={{url_for("auth.logout")}}>Logout</a></li>
        {% else %}
        <li><a class="active" href={{url_for("auth.signup")}}>Sign up</a></li>
      <li><a href={{url_for("auth.login")}}>Login</a></li>
      {% endif %}
      
    </ul>
    </div>
  </nav>
  <div class ="container">{% block content %}{% endblock %}</div>
  <script type="text/javascript" src={{url_for("static", filename="js/index.js")}}></script>
</body>
</html>

src/templates/classes.html
{% extends "base.html" %}
{% block title %} Classes - Attendy {% endblock %}

src/templates/index.html
{% extends "base.html" %}
{% block title %} Home - Attendy {% endblock %}
{% block head %}
<link rel="stylesheet" href={{url_for("static", filename="css/index.css")}}>
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
<div class ="welcome">
<h1 id="welcome" >Hello, {{user.full_name}}</h1>
<p class="subtitle">Welcome to Attendy!</p>
</div>
{% else %}
<div class="welcome">
<h1 id="welcome" >Hello, Guest User</h1>
<p class="subtitle">Welcome to Attendy!</p>
<p class="subtitle">Please <a href={{url_for("auth.login")}}>login</a> to continue!</p>
</div>
{% endif %}
<div class =""
{% endblock %}

src/templates/login.html
{% extends "base.html" %}
{% block title %} Login - Attendy {% endblock %}
{% block head %}
<link rel="stylesheet" href={{url_for("static", filename="css/login.css")}}>
{% endblock %}
{% block content %}
<div class="center">
    <h1>Login</h1>
    <form method="POST">
        <div class="text_field">
            <input type="text" name="email" id="email" required>
            <span></span>
            <label>Email</label>
        </div>
        <div class="text_field">
            <input type="password" name="password" id="password" required>
            <span></span>
            <label>Password</label>
        </div>
        <div class="forgot_password">Forgot password?</div>
        <input type="submit" name="submit">
        <div class="signup_link">
            Not registered? <a href={{url_for("auth.signup")}}>Signup</a>
        </div>
    </form>
</div>

{% endblock %}

src/templates/profile.html
{% extends "base.html" %}
{% block title %} Profile - Attendy {% endblock %}

src/templates/signup.html
{% extends "base.html" %}
{% block title %} Sign Up - Attendy {% endblock %}
{% block head %}
<link rel="stylesheet" href={{url_for("static", filename="css/login.css")}}>
{% endblock %}
{% block content %}
<div class="center">
    <h1>Sign Up</h1>
    <form method="POST">
        <div class="text_field">
            <input type="text" name="name" id="name" required>
            <span></span>
            <label>Full Name</label>
        </div>
        <div class="text_field">
            <input type="text" name="email" id="email" required>
            <span></span>
            <label>Email</label>
        </div>
        <div class="text_field">
            <input type="password" name="password1" id="password1"required>
            <span></span>
            <label>Password</label>
        </div>
        <div class="text_field">
            <input type="password" name="password2" id="password2" required>
            <span></span>
            <label>Confirm Password</label>
        </div>
        <input type="submit" name="submit">
        <div class="signup_link">
            Already registered? <a href={{url_for("auth.login")}}>Login</a>
        </div>
    </form>
</div>

{% endblock %}